from tkinter import *
root_window = Tk()
root_window.title("Daltonism")
root_window.geometry("400x400")
label = Label(text="Welcome", bg="grey", font=("Times New Roman", 20))
label.pack()
label = Label(text="1.             ", bg="green")
label.pack()
label = Label(text="2.             ", bg="red")
label.pack()
label = Label(text="3.             ", bg="purple")
label.pack()
label = Label(text="4.             ", bg="yellow")
label.pack()
button = Button(text="1.Button", bg="green")
button.pack()
button = Button(text="2.Button", bg="red")
button.pack()
button = Button(text="3.Button", bg="purple")
button.pack()
button = Button(text="4.Button", bg="yellow")
button.pack()
root_window.mainloop()